Vagrant.configure("2") do |config|

  # Глобальные установки:

  BOX_NAME       = "ubuntu/jammy64"
  NETWORK_PREFIX = "10.77.133"
  NETMASK        = "255.255.255.240"
  BOOT_TIMEOUT   = 600
  # Отключаем дефолт синх. директории
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # Унифицированное создание VM
  def create_vm(vm, params)
    # Базывоные настройки VM
    vm.vm.box          = BOX_NAME
    vm.vm.hostname     = params[:hostname]
    vm.vm.boot_timeout = BOOT_TIMEOUT
    # Private Network
    vm.vm.network "private_network",
      ip: "#{NETWORK_PREFIX}.#{params[:ip]}",
      netmask: NETMASK
    #publick_network
    if params[:public_network]
      vm.vm.network "public_network"
    end
    # sync folder
    if params[:sync_folder]

      vm.vm.synced_folder(
        "./#{params[:sync_folder]}",
        "/home/vagrant/#{params[:sync_folder]}"
      )

    end

    # Provision scripts

    vm.vm.synced_folder(
      "./provision",
      "/opt/provision",
      create: true
    )

    # Настройки virtualbox

    vm.vm.provider "virtualbox" do |vb|

      vb.name   = params[:name]
      vb.memory = params[:memory]
      vb.cpus   = params[:cpus]

    end

    #PROVISION
    vm.vm.provision "shell",
      path: params[:provision],
      args: params[:provision_args]

  end
   # postgresql vm

  config.vm.define "postgresql" do |postgresql|

    create_vm(postgresql,
      name: "postgresql",
      hostname: "postgresql",
      ip: 4,
      memory: 1024,
      cpus: 1,
      public_network: false,
      provision: "provision/postgres.sh"
    )

  end

  # ollama vm

  config.vm.define "ollama" do |ollama|

    create_vm(ollama,
      name: "ollama",
      hostname: "ollama",
      ip: 3,
      memory: 8192,
      cpus: 2,
      sync_folder: "ollama",
      public_network: false,
      provision: "provision/ollama.sh"
    )

  end
    # n8n VM
  config.vm.define "n8n" do |n8n|

    create_vm(n8n,
      name: "n8n",
      hostname: "n8n",
      ip: 2,
      memory: 2048,
      cpus: 1,
      sync_folder: "n8n",
      public_network: false,
      provision: "provision/docker.sh",
      provision_args: "n8n"
    )

  end

  # wikijs vm

  config.vm.define "wikijs" do |wikijs|

    create_vm(wikijs,
      name: "wikijs",
      hostname: "wikijs",
      ip: 5,
      memory: 1024,
      cpus: 1,
      sync_folder: "wikijs",
      public_network: false,
      provision: "provision/docker.sh",
      provision_args: "wikijs"
    )

  end

end