services:

  wikijs:
    image: requarks/wiki:2
    container_name: wikijs
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: 10.77.133.4
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs
      DB_NAME: wikijs_db
    volumes:
      - ./wikijs-data:/var/lib/wiki